name             'simple-nexus'
maintainer       'Yauhen Artsiukhou'
maintainer_email 'jsirex@gmail.com'
license          'Apache'
description      'Installs/Configures simple-nexus. No less. No more.'
long_description 'Installs/Configures simple-nexus. No less. No more.'
issues_url       'https://github.com/jsirex/simple-nexus-cookbook/issues'
source_url       'https://github.com/jsirex/simple-nexus-cookbook'
version          '0.1.0'

supports 'debian'
supports 'ubuntu'
supports 'centos'

depends 'ark'
